@Host = http://localhost:5196
@UserIdJohn = "a0ffc8cf-43f9-4b88-951d-fffb95f86d2c"
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGZmYzhjZi00M2Y5LTRiODgtOTUxZC1mZmZiOTVmODZkMmMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoiam9obi5kb2VAZGVtby5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXJraW5nQWRtaW5pc3RyYXRvciIsImp0aSI6IjAxN2Q5NGY5LTc2YjUtNDY1OC1hMDY1LWU0NGNjMzFjZTYzYyIsImV4cCI6MTc3MjQ1NDYxMywiaXNzIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBTZXJ2ZXIiLCJhdWQiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIENsaWVudCJ9.HqC2wDdN64wKAhQJ1EXs66mdq76WcghXMFiTNBvbw5Q

POST {{Host}}/api/users/change-password
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "userId": {{UserIdJohn}},
  "currentPassword": "Secret&password123",
  "newPassword": "Secret/password123"
}
###