@Host = http://localhost:5196

POST {{Host}}/api/users/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@demo.com",
  "phone": "+36112312312",
  "password": "Secret/password123",
  "role": 2
}
###