@Host = http://localhost:5196

POST {{Host}}/api/users/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@demo.com",
  "phone": "+36112312312",
  "password": "Secret/password123",
  "role": 2
}
###

POST {{Host}}/api/users/register
Content-Type: application/json

{
  "firstName": "Kate",
  "lastName": "White",
  "email": "kate.white@demo.com",
  "phone": "+36112312312",
  "password": "Secret/password123",
  "role": 2
}
###

POST {{Host}}/api/users/register
Content-Type: application/json

{
  "firstName": "Mark",
  "lastName": "Dark",
  "email": "mark.dark@demo.com",
  "phone": "+36112312312",
  "password": "Secret/password123",
  "role": 0
}
###