@Host = http://localhost:5196
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGZmYzhjZi00M2Y5LTRiODgtOTUxZC1mZmZiOTVmODZkMmMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoiam9obi5kb2VAZGVtby5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXJraW5nQWRtaW5pc3RyYXRvciIsImp0aSI6ImY0NDFlYWZiLTdiMzItNDllYi1iZGI2LWU1MTcwYmJlYmExNyIsImV4cCI6MTc3MjA0Mjk2MywiaXNzIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBTZXJ2ZXIiLCJhdWQiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIENsaWVudCJ9.hKoqw3zhE6hQGdtjfdgsOCejd13Ne9iUALrBlZdZPwQ
@UserId = a0ffc8cf-43f9-4b88-951d-fffb95f86d2c

GET {{Host}}/api/reservations?Dates=2026-02-24&Dates=2026-02-25
Authorization: Bearer {{Token}}
Content-Type: application/json

###

GET {{Host}}/api/reservations/{{UserId}}?includeExpired=true
Authorization: Bearer {{Token}}
Content-Type: application/json

###