@Host = http://localhost:5196
@UserIdJohn = a0ffc8cf-43f9-4b88-951d-fffb95f86d2c
@UserIdKate = bc9ff325-b950-49e2-b7b2-dfcf7eb87d70
@ParkingSpotId = 07ed9261-e9d8-450a-8c3e-d070c00ed103
@Date1 = 2026-02-23
@Date2 = 2026-02-24
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYzlmZjMyNS1iOTUwLTQ5ZTItYjdiMi1kZmNmN2ViODdkNzAiLCJnaXZlbl9uYW1lIjoiS2F0ZSIsImVtYWlsIjoia2F0ZS53aGl0ZUBkZW1vLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBhcmtpbmdBZG1pbmlzdHJhdG9yIiwianRpIjoiN2RmYzA1YWQtNDA1Mi00OTBlLTgzN2QtOGYxZTA1YjZhNmZmIiwiZXhwIjoxNzcwODAxNjI4LCJpc3MiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIFNlcnZlciIsImF1ZCI6IlBhcmtpbmcgTWFuYWdlbWVudCBTeXN0ZW0gQ2xpZW50In0.mAv0WdQdG43_489eEK8TscWr2s2YV-BMOd6LrWzPBQ0

POST {{Host}}/api/reservations/reserve-parkingspots
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "userId": "{{UserIdJohn}}",
  "dates": [
    "{{Date1}}",
    "{{Date2}}"
  ]
}
###

POST {{Host}}/api/reservations/reserve-parkingspots
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "userId": "{{UserIdKate}}",
  "dates": [
    "{{Date1}}",
    "{{Date2}}"
  ]
}
###