@Host = http://localhost:5196

POST {{Host}}/api/parkingspots
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTJjYWZkMS1mZDM2LTQxYWQtOTBlMy1lMDlhMjM3MTE4M2IiLCJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoiam9obi5kb2VAZGVtby5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXJraW5nQWRtaW5pc3RyYXRvciIsImp0aSI6ImJkODI5NmQzLWJkMTAtNGYwNC05YWIxLTlkMjM2ZjFjYjQzNCIsImV4cCI6MTc3MDIxNjQxMiwiaXNzIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBTZXJ2ZXIiLCJhdWQiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIENsaWVudCJ9.YSPICXD5VJxIZsEAw6ucWc41b8V3oG9N_pRilQcFl2w

{
    "name": "P01",
    "description": "In front of the main entrance.",
    "state": 2
}
###