@Host = http://localhost:5196
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGZmYzhjZi00M2Y5LTRiODgtOTUxZC1mZmZiOTVmODZkMmMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoiam9obi5kb2VAZGVtby5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXJraW5nQWRtaW5pc3RyYXRvciIsImp0aSI6IjE0ZDRkYzBkLTI0NjYtNDYzNS04Y2E5LTQ1MmExYjMwZjNkYSIsImV4cCI6MTc3MDgxMDE2NywiaXNzIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBTZXJ2ZXIiLCJhdWQiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIENsaWVudCJ9.VGS0UuD38jyU5GrBHc3jppnfVlmmLuXNTDAU29-lOxo
@ParkingSpotId = ae825a0d-35f4-467c-bcd6-da3157389f42
@ManagerId = bc9ff325-b950-49e2-b7b2-dfcf7eb87d70

POST {{Host}}/api/parkingspots/assign-dedicated-parking-spot
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "parkingSpotId": "{{ParkingSpotId}}",
  "managerId": "{{ManagerId}}"
}
###