@Host = http://localhost:5196
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGZmYzhjZi00M2Y5LTRiODgtOTUxZC1mZmZiOTVmODZkMmMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoiam9obi5kb2VAZGVtby5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXJraW5nQWRtaW5pc3RyYXRvciIsImp0aSI6ImVmYTc0YmU3LTNmNjUtNDUwOS1iNDNmLWM4MzI2ZDVmNjRhNiIsImV4cCI6MTc3MDYzNTA4NywiaXNzIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBTZXJ2ZXIiLCJhdWQiOiJQYXJraW5nIE1hbmFnZW1lbnQgU3lzdGVtIENsaWVudCJ9.ozShgd0479ClTI4Re5bbnO42fRT7v1XRBPg7JZ9GMvg
@ParkingSpotId = 
@ManagerId = 

POST {{Host}}/api/parkingspots/assigndedicatedparkingspot
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "parkingSpotId": "{{ParkingSpotId}}",
  "managerId": "{{ManagerId}}"
}
###