@Host = http://localhost:5196
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYzRkYTRjMy0xOGI2LTQ0YmQtOTNiZS05MDUzNjAxM2JiYTAiLCJnaXZlbl9uYW1lIjoiTWFyayIsImVtYWlsIjoibWFyay5kYXJrQGRlbW8uY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJqdGkiOiI3YjAxOGYyMy0xOTZmLTQ1MzktYTRkYS01OGEwMmRlOWNjMTQiLCJleHAiOjE3NzE5NTc0MzgsImlzcyI6IlBhcmtpbmcgTWFuYWdlbWVudCBTeXN0ZW0gU2VydmVyIiwiYXVkIjoiUGFya2luZyBNYW5hZ2VtZW50IFN5c3RlbSBDbGllbnQifQ.kbBn2sJ9KWRdoIC857iPqzmcgVhVIDJuSkkauQCrhtI

GET {{Host}}/api/parkingspots
Content-Type: application/json
Authorization: Bearer {{Token}}

###